name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron:  '55 6 * * *'
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
    runs-on: ubuntu-latest
    env:
      GIT_SSL_NO_VERIFY: "true"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Install nix
      uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-platforms = i686-linux aarch64-linux arm-linux
    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: xddxdd
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build nix packages
      run: |
        nix flake update
        nix run .#ci -- ${{ matrix.system }}

  update-nur:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=xddxdd"
